### PR TITLE
tpm2_policyauthorize: Fix incorrect text in error logging

### LINKED ISSUE #1658: tpm2_policyauthorize: weird options
-c is mentioned in is_checkinput_options_ok() but their is no -c option. Also, perhaps input should be an argument.

### PR DESCRIPTION
**Pull request by idesai**
Fixes #1658 

Fixed option descriptions in the is_check_input_options_ok routines
Changed the global variable from verifying_pubkey_path to verifying_pubkey_name_path.

Signed-off-by: Imran Desai <imran.desai@intel.com>

### CODE REVIEW

File: tools/tpm2_policyauthorize.c [hunk 1]
```diff
@@ -16,7 +16,7 @@ struct tpm2_policyauthorize_ctx {
    //File path for the policy qualifier data
    const char *qualifier_data_path;
    //File path for the verifying public key name
-   const char *verifying_pubkey_path;
+   const char *verifying_pubkey_name_path;
```
Comment (williamcroberts) [inline tools/tpm2_policyauthorize.c]: You should have split this up in 2 patches, I won't nack it this time, but I will next time. 1 patch for the variable rename and 1 patch for the actual logging error fix.
