### PR TITLE
tpm2_eventlog: Format partitions correctly

### LINKED ISSUE #2746: tpm2_eventlog: Partitions are displayed incorrectly
When running `tpm2 eventlog ./eventlog.bin` I get the following for the `EV_EFI_GPT_EVENT` `Partions:`
```yaml
Partitions:
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "E"
```

Note that the same partition is printed 3 times and the `PartitionName:` is only one character.

I would expect an output that looks like:
```yaml
Partitions:
- PartitionTypeGUID: 28732ac1-1ff8-d211-ba4b-00a0c93ec93b
  UniquePartitionGUID: 1346501a-b519-444b-a83d-d926d40daa1c
  StartingLBA: 0x800
  EndingLBA: 0x807ff
  Attributes: 0x0
  PartitionName: "EFI System"
- PartitionTypeGUID: 0f889da1-fc05-3b4d-a006-743f0f84911e
  UniquePartitionGUID: 2406fec3-b73d-f444-941e-49e6823d5a30
  StartingLBA: 0x80800
  EndingLBA: 0x1d24594e
  Attributes: 0x0
  PartitionName: "Linux RAID"
- PartitionTypeGUID: af3dc60f-8384-7247-8e79-3d69d8477de4
  UniquePartitionGUID: d355ca07-baef-a743-aea7-334c379e6b70
  StartingLBA: 0x1d246000
  EndingLBA: 0x1dcf328e
  Attributes: 0x0
  PartitionName: "Linux filesystem"
```

### PR DESCRIPTION
**Pull request by josephlr**
Fixes #2746 

Now each partition is printed separately, and we correctly display the UTF16 strings in the partition names.

This change required creating a helper struct:
```c
typedef struct {
    char16_t c;
} PACKED UTF16_CHAR;
```
so that we could pass the address of our UFT16 buffer to a helper function without invoking undefined behavior.

I tested this on some sample eventlogs and it now seems to produce correct output (with `--eventlog-version=2`).

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

**Comment by idesai** [comment]
@josephlr thank you. Can you also please add the eventlog binary you tested on to the [test-fixtures](https://github.com/tpm2-software/tpm2-tools/tree/master/test/integration/fixtures) and update the integration tests?

File: lib/efi_event.h [hunk 1]
```diff
@@ -147,7 +152,7 @@ typedef struct {
     UINT64 StartingLBA;
     UINT64 EndingLBA;
     UINT64 Attributes;
-    BYTE PartitionName[72];
+    UTF16_CHAR PartitionName[36];
```
Comment (idesai) [inline lib/efi_event.h:155]: @josephlr, what is the magic number 36?

**Comment by josephlr** [comment]
> @josephlr thank you. Can you also please add the eventlog binary you tested on to the [test-fixtures](https://github.com/tpm2-software/tpm2-tools/tree/master/test/integration/fixtures) and update the integration tests?

Added some additional Event Logs, and updated the integration tests to use `--eventlog-version=2` for those logs. I also updated the `.gitignore` and `test/.gitignore` files to properly include/exclude generated files (my change #2743 was not correct in this regard).

**Comment by josephlr** [comment]
@idesai it looks like the `master-tss-build-test`s are failing for unrelated reasons.

File: lib/efi_event.h (hunk 1 above)
Comment (josephlr) [reply lib/efi_event.h:166]: That's just the definition in the EFI spec:
```c
typedef struct {
    EFI_GUID PartitionTypeGUID;
    EFI_GUID UniquePartitionGUID;
    EFI_LBA StartingLBA;
    EFI_LBA EndingLBA;
    UINT64 Attributes;
    CHAR16 PartitionName[36];
} PACKED EFI_PARTITION_ENTRY;
```

See section `5.3.3` of the [UEFI Spec v2.9](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf).

The GPT format chose `36` so that `sizeof(EFI_PARTITION_ENTRY) == 128` ([godbolt link](https://godbolt.org/z/4hxbsYja6)) so that the entry fits exactly in two x86 cache lines.

Comment (josephlr) [reply lib/efi_event.h:166]: @idesai, do you want me to add a comment explaining this, or is that implied from the structure of this file?

Comment (idesai) [reply lib/efi_event.h:166]: @josephlr yes please.

**Comment by idesai** [comment]
> @idesai it looks like the `master-tss-build-test`s are failing for unrelated reasons.

@josephlr, the CI is now fixed. Can you please rebase your PR on current master.
Thank you for adding the test fixtures and updating the test.

File: lib/efi_event.h (hunk 1 above)
Comment (josephlr) [reply lib/efi_event.h:167]: Done

**Comment by josephlr** [comment]
> @josephlr, the CI is now fixed. Can you please rebase your PR on current master.

Done, thanks for fixing the CI, looks like everything is passing now.
