### PR TITLE
Fixes for ECC ecdaa signing scheme

### LINKED ISSUE #2071: ECDAA signatures count defaults to 4
ECDAA count defaults to 4, which doesn't make a whole lot of sense, as it checks against the commit index modified by tpm2_commit. We either need to find a way to default this, or ensure its specified.

### PR DESCRIPTION
**Pull request by idesai**
Fixes #2071

- [x] Fix the default value for ecdaa commit counter — Should be 0.
- [x] Add a ECC ecdaa signing test
- [x] Add more tests to check signing with commit-counter values other than default 0.
- [x] Sanitize **tpm2_sign** input options — Do not allow -f when ecdaa chosen.
- [x] Sanitize commit-counter value specified as ecdaa# in sign and key creation.
~~- [ ] Add signature verification~~
Signed-off-by: Imran Desai <imran.desai@intel.com>

### CODE REVIEW

File: lib/tpm2_alg_util.c [hunk 1]
```diff
@@ -204,12 +204,12 @@ static alg_parser_rc handle_scheme_sign(const char *scheme,
...
-             * ECDAA has both a count and hashing algorithm, scheme
-             * could either be pointing to a null byte or a number,
-             * we need a number
+             * ECDAA has both a commit-counter value and hashing algorithm.
+             * The default commit-counter value is set to zero to use the first
+             * commit-id.
              */
             if (scheme[0] == '\0') {
-                scheme = "4";
+                scheme = "0";
```
Comment (williamcroberts) [inline lib/tpm2_alg_util.c:212]: So 0 is a sane default? Makes sense, you just did something to bump the commit index (slot that has the ECDA KEY) and thus you want to use it in a subsequent sign.

File: test/integration/tests/sign.sh [hunk 2]
```diff
@@ -270,6 +270,17 @@ do
     )
 done
 
+# Test signing with ecdaa scheme
+head -c30 /dev/urandom > test.rnd
+shasum -a 256 test.rnd | awk '{ print "000000 " $1 }' | xxd -r -c 32 > test.dgst
```
Comment (williamcroberts) [inline test/integration/tests/sign.sh:275]: head -c30 /dev/urandom | openssl dgst -sha256 -binary > test.dgst

File: test/integration/tests/sign.sh [hunk 3]
```diff
@@ -270,6 +270,17 @@ do
...
+tpm2 clear
+tpm2 createprimary -Q -C o -c prim.ctx -g sha256 -G rsa
+tpm2 create -Q -g sha256 -G ecc256:ecdaa -u key.pub -r key.priv -C prim.ctx
+tpm2 load -C prim.ctx -u key.pub -r key.priv -n key.name -c key.ctx
+tpm2 readpublic -c key.ctx --format=pem -o key.pem
+tpm2 commit -c key.ctx -t commit.ctr --eccpoint-K K.bin --eccpoint-L L.bin -u E.bin
+tpm2 sign -c key.ctx -g sha256 -o test.sig test.rnd -s ecdaa
+
```
Comment (williamcroberts) [inline test/integration/tests/sign.sh:283]: TODO verify? TODO run it again and make sure that index's other than 0 work.

File: lib/tpm2_alg_util.c (hunk 1 above)
Comment (idesai) [reply lib/tpm2_alg_util.c:212]: Correct.

**Comment by idesai** [comment]
> Fixes #2071
> 
> * [x]  Fix the default value for ecdaa commit counter — Should be 0.
> * [x]  Add a ECC ecdaa signing test
> * [x]  Add more tests to check signing with commit-counter values other than default 0.
> * [x]  Sanitize **tpm2_sign** input options — Do not allow -f when ecdaa chosen.
> * [x]  Sanitize commit-counter value specified as ecdaa# in sign and key creation.
>   ~- [ ] Add signature verification~
>   Signed-off-by: Imran Desai [imran.desai@intel.com](mailto:imran.desai@intel.com)

ECDAA signature verification support to be added later via issue #2180
