### PR TITLE
Fix issue where oaep hash algorithm was hardcoded

### LINKED ISSUE #2691: tpm2_rsadecrypt with OAEP padding
I'm trying to use tpm2_rsadecrypt with OAEP padding, but it fails with this error:
```
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x000002c3)
ERROR: Esys_RSA_Decrypt(0x2C3) - tpm:parameter(2):hash algorithm not supported or not appropriate
ERROR: Unable to run tpm2_rsadecrypt
```
I'm able to use default padding (PKCSV1.5):
```
# tpm2_readpublic -c 0x81000005 -o key_pub.pem --f pem --quiet
# openssl rsautl -encrypt -inkey key_pub.pem -pubin -in msg.txt -out msg.enc
# tpm2_rsadecrypt -c 0x81000005 -o msg.out msg.enc
```

but when I try the same with OAEP it fails:
```
# tpm2_readpublic -c 0x81000005 -o key_pub.pem --f pem --quiet
# openssl rsautl -encrypt -oaep -inkey key_pub.pem -pubin -in msg.txt -out msg.enc
# tpm2_rsadecrypt -c 0x81000005 -s oaep -o msg.out msg.enc
WARNING:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:301:Esys_RSA_Decrypt_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_RSA_Decrypt.c:102:Esys_RSA_Decrypt() Esys Finish ErrorCode (0x000002c3)
ERROR: Esys_RSA_Decrypt(0x2C3) - tpm:parameter(2):hash algorithm not supported or not appropriate
ERROR: Unable to run tpm2_rsadecrypt
```

The key is created and persisted as follows:
```
tpm2_clear
tpm2_createprimary \
	--hash-algorithm=sha256 \
	--key-algorithm=rsa \
	--key-context="primary.ctx" \
	--quiet
tpm2_create \
	--parent-context="primary.ctx" \
	--hash-algorithm=sha256 \
	--key-algorithm=rsa \
	--private="key.priv" \
	--public="key.pub" \
	--quiet
tpm2_load \
	--parent-context="primary.ctx" \
	--public="key.pub" \
	--private="key.priv" \
	--key-context="key.ctx" \
	--quiet
tpm2_evictcontrol 0x81000005 \
	--hierarchy=o \
	--object-context="key.ctx" \
	--quiet
```

also tried to create key with oaep-sha256 scheme, but got this error:
```
# tpm2_create -C primary.ctx -G rsa2048:oaep-sha256 -u key.pub -r key.priv
ERROR: Could not handle algorithm spec: "rsa2048:oaep-sha256"
ERROR: Unable to run tpm2_create
```

 
I'm using version 4.1.1
```
tool="tpm2_rsadecrypt" version="4.1.1" tctis="libtss2-tctildr" tcti-default=tcti-device
```

Am I missing something or my TPM doesn't support oaep?

### PR DESCRIPTION
**Pull request by idesai**
Fixes #2691 

With this one the scheme halg can be specified in an already known nice name format.
Eg. oaep-sha1

### CODE REVIEW

File: tools/tpm2_rsadecrypt.c [hunk 1]
```diff
@@ -1,6 +1,7 @@
 /* SPDX-License-Identifier: BSD-3-Clause */
 
 #include <stdlib.h>
+#include <string.h>
```
Comment (idesai) [inline tools/tpm2_rsadecrypt.c:4]: No need for this library header
