### PR TITLE
tpm2_changeauth: only change hierachy specified

### LINKED ISSUE #1183: Please change auth seperately in tpm2_takeownership.c, because test_tpm2_takeownership.sh will report fail if the auth of TPM2_RH_LOCKOUT has already been set.
In tpm2_takeownership.c, the auth of TPM2_RH_OWNER, TPM2_RH_ENDORSEMENT and TPM2_RH_LOCKOUT will be changed together in one call. But it will report error when TPM2_RH_LOCKOUT has been set that test case test_tpm2_takeownership.sh will fail.
Considering the following step:
1. change TPM2_RH_LOCKOUT auth, successfully.
$ tpm2_takeownership -l newpswd
2. change TPM2_RH_OWNER auth, failed for the error. 
$ tpm2_takeownership -o newpswd
ERROR: Could not change hierarchy for Lockout. TPM Error:0x921
ERROR: Unable to run tpm2_takeownership
3. Actually, tpm2_getcap shows TPM2_RH_OWNER auth has been changed. 
$ tpm2_getcap --capability="properties-variable"
TPM2_PT_PERSISTENT:
  ownerAuthSet:              set
  endorsementAuthSet:        clear
  lockoutAuthSet:            set
  reserved1:                 clear
  disableClear:              clear
  inLockout:                 clear
  tpmGeneratedEPS:           set
  reserved2:                 clear
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  set
  shEnable:                  set
  ehEnable:                  set
  phEnableNV:                set
  reserved1:                 clear
  orderly:                   clear
TPM2_PT_TPM2_HR_NV_INDEX:          0x00000000
TPM2_PT_HR_LOADED:            0x00000000
TPM2_PT_HR_LOADED_AVAIL:      0x00000003
TPM2_PT_HR_ACTIVE:            0x00000000
TPM2_PT_HR_ACTIVE_AVAIL:      0x00000040
TPM2_PT_TPM2_HR_TRANSIENT_AVAIL:   0x00000003
TPM2_PT_TPM2_HR_PERSISTENT:        0x00000000
TPM2_PT_TPM2_HR_PERSISTENT_AVAIL:  0x00000006
TPM2_PT_NV_COUNTERS:          0x00000000
TPM2_PT_NV_COUNTERS_AVAIL:    0x00000019
TPM2_PT_ALGORITHM_SET:        0xffffffff
TPM2_PT_LOADED_CURVES:        0x00000003
TPM2_PT_LOCKOUT_COUNTER:      0x00000000
TPM2_PT_MAX_AUTH_FAIL:        0x00000005
TPM2_PT_LOCKOUT_INTERVAL:     0x00000006
TPM2_PT_LOCKOUT_RECOVERY:     0x00000007
TPM2_PT_NV_WRITE_RECOVERY:    0x00000000
TPM2_PT_AUDIT_COUNTER_0:      0x00000000
TPM2_PT_AUDIT_COUNTER_1:      0x00000000

### PR DESCRIPTION
**Pull request by joshuagl**
Backport of the change in 7ace0ea to the 3.X branch.

Only send a changeauth command if the hiearchy is specified.
This corrects behavior of attempting to change a non-specified hierarchy.

Fixes #1183

Signed-off-by: Joshua Lock <joshua.g.lock@intel.com>

### CODE REVIEW

**Comment by joshuagl** [comment]
Not sure if something funky is going on with Travis. It doesn't look like the last build completed download/extracting the container...

File: tools/tpm2_takeownership.c [hunk 1]
```diff
@@ -111,12 +120,23 @@ static bool change_auth(TSS2_SYS_CONTEXT *sapi_context,
 static bool change_hierarchy_auth(TSS2_SYS_CONTEXT *sapi_context) {
 
     // change owner, endorsement and lockout auth.
-    return change_auth(sapi_context, &ctx.passwords.owner,
-                "Owner", TPM2_RH_OWNER)
-        && change_auth(sapi_context, &ctx.passwords.endorse,
-                "Endorsement", TPM2_RH_ENDORSEMENT)
-        && change_auth(sapi_context, &ctx.passwords.lockout,
-                "Lockout", TPM2_RH_LOCKOUT);
+    bool result = true;
```
Comment (williamcroberts) [inline tools/tpm2_takeownership.c]: at some point we need to support handle as well so you can change loaded tpm objects auth value.
