### PR TITLE
tools/tpm2_evictconrol: fix for call to Esys_TR_Close on bad handle

### LINKED ISSUE #2254: tpm2_evictcontrol calls Esys_TR_Close on bad handle
So this issue cropped up in a tpm2-pkcs11 bug report:
```
> [test@automation-test ~]$ tpm2_ptool init Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/tpm2_pkcs11/commandlets_store.py",
> line 87, in __call__
>     tr_handle = tpm2.evictcontrol(ownerauth, ctx)
>   File "/usr/lib/python3.8/site-packages/tpm2_pkcs11/tpm2.py", line 48, in
> evictcontrol
>     raise RuntimeError("Could not execute tpm2_evictcontrol: %s",
> RuntimeError: ('Could not execute tpm2_evictcontrol: %s',
> b'WARNING:esys:src/tss2-
> esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
> \nERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys
> Finish ErrorCode (0x0000014b) \nERROR: Esys_EvictControl(0x14B) -
> tpm:error(2.0): insufficient space for NV allocation\nERROR:esys:src/tss2-
> esys/esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018).
> \nERROR: Esys_TR_Close(0x70018) - esapi:The ESYS_TR resource object is
> bad\nERROR: Unable to run tpm2_evictcontrol\n') ('Could not execute
> tpm2_evictcontrol: %s', b'WARNING:esys:src/tss2-
> esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error
> \nERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys
> Finish ErrorCode (0x0000014b) \nERROR: Esys_EvictControl(0x14B) -
> tpm:error(2.0): insufficient space for NV allocation\nERROR:esys:src/tss2-
> esys/esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018).
> \nERROR: Esys_TR_Close(0x70018) - esapi:The ESYS_TR resource object is
> bad\nERROR: Unable to run tpm2_evictcontrol\n')
```

I think this is because on error we `goto out` with variable `evicted` set to false:
https://github.com/tpm2-software/tpm2-tools/blob/90f3fc0ff24b2253b1cfe8fde0c432484917224f/tools/tpm2_evictcontrol.c#L175-L179

and

https://github.com/tpm2-software/tpm2-tools/blob/90f3fc0ff24b2253b1cfe8fde0c432484917224f/tools/tpm2_evictcontrol.c#L201-L206

I think if we just return on error immediately, we'll be fine.

### PR DESCRIPTION
**Pull request by idesai**
Fixes #2254

Signed-off-by: Imran Desai <imran.desai@intel.com>

### CODE REVIEW

File: tools/tpm2_evictcontrol.c [hunk 1]
```diff
@@ -136,34 +131,36 @@ static tool_rc tpm2_tool_onrun(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
...
         LOG_WARN("Calculating cpHash. Exiting without evicting objects.");
-        tool_rc rc = tpm2_evictcontrol(ectx, &ctx.auth_hierarchy.object,
+
+        TPM2B_DIGEST cp_hash = { .size = 0 };
+        rc = tpm2_evictcontrol(ectx, &ctx.auth_hierarchy.object,
         &ctx.to_persist_key.object, ctx.persist_handle, &out_tr, &cp_hash);
         if (rc != tool_rc_success) {
             return rc;
         }
+
```
Comment (williamcroberts) [inline tools/tpm2_evictcontrol.c:158]: formatting change to another commit

File: tools/tpm2_evictcontrol.c [hunk 2]
```diff
@@ -136,34 +131,36 @@ static tool_rc tpm2_tool_onrun(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
...
         bool result = files_save_digest(&cp_hash, ctx.cp_hash_path);
         if (!result) {
             rc = tool_rc_general_error;
         }
+
```
Comment (williamcroberts) [inline tools/tpm2_evictcontrol.c:163]: same formatting change to a separate commit
