### PR TITLE
tpm2_eventlog: read eventlog file in chunks

### LINKED ISSUE #2775: tpm2_eventlog: ERROR: Unable to run tpm2_eventlog
I am having this error under recent kernels (5.12.9 and 5.12.10) and in different distributions (openSUSE Tumbleweed and Fedora 34 Server). Also I can reproduce it from 5.1 and master:

```
-- openSUSE Tumbleweed
# tpm2_eventlog -v
tool="tpm2_eventlog" version="5.1" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

# uname -a
Linux dhcp189 5.12.9-1-default #1 SMP Thu Jun 3 07:44:58 UTC 2021 (f17eb01) x86_64 x86_64 x86_64 GNU/Linux

-- Fedora 34 (Server Edition)
# tpm2_eventlog -v
tool="tpm2_eventlog" version="5.1" tctis="libtss2-tctildr" tcti-default=tcti-abrmd

# uname -a
Linux fedora 5.12.10-300.fc34.x86_64 #1 SMP Thu Jun 10 14:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Doing strace seems that could be a problem in fseek. According to the bug created for the openSUSE project (https://bugzilla.suse.com/show_bug.cgi?id=1187360#c2) fseek is used to identify the size of the file, and this should not work with securefs.

```
# strace tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements
...
futex(0x7fba8bafbe18, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/sys/kernel/security/tpm0/binary_bios_measurements", O_RDONLY) = 3
lseek(3, 0, SEEK_CUR)                   = 0
newfstatat(3, "", {st_mode=S_IFREG|0440, st_size=0, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0440, st_size=0, ...}, AT_EMPTY_PATH) = 0
lseek(3, 0, SEEK_SET)                   = 0
lseek(3, 0, SEEK_SET)                   = 0
close(3)                                = 0
write(2, "ERROR: ", 7ERROR: )                  = 7
write(2, "Unable to run eventlog", 22Unable to run eventlog)  = 22
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

### PR DESCRIPTION
**Pull request by aplanas**
The eventlog file lives is securityfs, that do not return the file size.
The current implementation first try to do a "fseek(fp, 0, SEEK_END)"
for this file, and this will always return 0.

This generate an error, and tpm2_eventlog exit with:

ERROR: Unable to run tpm2_eventlog

This patch replace the reading logic, now reading in chunks of 16KB and
reallocating the buffer if needed. Also introduces a new function in
files.c ("files_read_bytes_chunk") that helps counting the total read
size, that now is different from the ammount of allocated memory.

Fixes #2775

Signed-off-by: Alberto Planas <aplanas@suse.com>

### CODE REVIEW

**Comment by aplanas** [comment]
Please, review carefully, I do not trust my C.

File: tools/misc/tpm2_eventlog.c [hunk 1]
```diff
@@ -72,37 +74,35 @@ static tool_rc tpm2_tool_onrun(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
...
+    unsigned long size = 0;
+    while (files_read_bytes_chunk(fileptr, eventlog, CHUNK_SIZE, &size)) {
+        UINT8 *eventlog_tmp = realloc(eventlog, size + CHUNK_SIZE);
+        if (eventlog_tmp == NULL){
+            LOG_ERR("failed to allocate %lu bytes: %s", size + CHUNK_SIZE, strerror(errno));
+            rc = tool_rc_general_error;
+            goto out;
+        }
+        eventlog = eventlog_tmp;
     }
```
Comment (idesai) [inline tools/misc/tpm2_eventlog.c:101]:
```suggestion
    do {
        is_file_read = files_read_bytes_chunk(fileptr, eventlog, CHUNK_SIZE, &size);
        UINT8 *eventlog_tmp = realloc(eventlog, size + CHUNK_SIZE);
        if (!eventlog_tmp){
            LOG_ERR("failed to allocate %lu bytes: %s", size + CHUNK_SIZE, strerror(errno));
            rc = tool_rc_general_error;
            goto out;
        }
        eventlog = eventlog_tmp;
    } while (is_file_read);
```

Comment (idesai) [reply tools/misc/tpm2_eventlog.c:101]: Don't hide function returns in the loop statement

Comment (aplanas) [reply tools/misc/tpm2_eventlog.c]: Yes. Done.

File: tools/misc/tpm2_eventlog.c [hunk 2]
```diff
@@ -72,37 +74,36 @@ static tool_rc tpm2_tool_onrun(ESYS_CONTEXT *ectx, tpm2_option_flags flags) {
...
-    tool_rc rc = tool_rc_success;
-    FILE *fileptr = fopen(filename, "rb");
-    if (!fileptr) {
-        rc = tool_rc_general_error;
-        goto out;
-    }
-
-    ret = files_read_bytes(fileptr, eventlog, size);
+    unsigned long size = 0;
+    do {
```
Comment (idesai) [inline tools/misc/tpm2_eventlog.c:93]:
```suggestion
    unsigned long size = 0;
    bool is_file_read = fale;
    do {
```

File: lib/files.h [hunk 3]
```diff
@@ -571,6 +571,21 @@ bool files_read_64(FILE *out, UINT64 *data);
...
+/**
+ * Reads len bytes from a file and set the read length.
+ * @param out
+ *  The file to read from.
+ * @param data
+ *  The buffer to read into, only valid on a True return.
+ * @param size
+ *  The number of bytes to read.
+ * @param read_size
+ *  Total number of bytes readed.
```
Comment (idesai) [inline lib/files.h:583]:
```suggestion
 *  Total number of bytes read.
```

**Review by idesai — CHANGES_REQUESTED** [review]

File: tools/misc/tpm2_eventlog.c (hunk 2 above)
Comment (aplanas) [reply tools/misc/tpm2_eventlog.c]: Oh thanks. Done.

File: lib/files.h (hunk 3 above)
Comment (aplanas) [reply lib/files.h]: Done.

**Review by idesai — APPROVED** [review]
