### PR TITLE
tpm2_getekcertificate.c: Fix issue with TPM_RNG_EPS bit comparison

### LINKED ISSUE #1697: Questionable check for TPM_RNG_EPS in tpm2_getekcertificate.c
In tpm2_getekcertificate.c, there's logic to check if an Intel PTT's Endorsement Primary Seed (EPS) was generated by the PTT or by the manufacturer:

https://github.com/tpm2-software/tpm2-tools/blob/5f9c9e9abbb38f3c6f82d091583ec0bb4acb5bd0/tools/tpm2_getekcertificate.c#L350-L366

In particular, it's using an equality comparison for the value of the TPM_PT_PERMANENT property with 0x400. However, TPM_PT_PERMANENT is a bitset property, so I think it should be using a bit-test operation instead (e.g., `xxx.value & TPM_RNG_EPS` or `(xxx.value & TPM_RNG_EPS) != 0`).

For comparison, INTEL-SA-00086-Linux-Recovery-Tools uses a bit-test operation: https://github.com/intel/INTEL-SA-00086-Linux-Recovery-Tools/blob/master/Intel-SA-00086-Recovery-Utility.c#L429

/cc @idesai who added the above code to tpm2_getekcertificate.c in https://github.com/tpm2-software/tpm2-tools/commit/0df61fcb928e6cf762b08e37312d70edd5f539ec

### PR DESCRIPTION
**Pull request by idesai**
Fixes #1697

The test is using an equality comparison for the value of
TPM_PT_PERMANENT property with 0x400 whic is a bitset property

Signed-off-by: Imran Desai <imran.desai@intel.com>

### CODE REVIEW

File: tools/tpm2_getekcertificate.c [hunk 1]
```diff
@@ -281,8 +281,8 @@ static bool on_option(char key, char *value) {
         break;
     case 'X':
         ctx.SSL_NO_VERIFY = 1;
-        LOG_WARN(
-                "TLS communication with the said TPM manufacturer server setup with SSL_NO_VERIFY!");
+        LOG_WARN("TLS communication with the said TPM manufacturer server setup"
+                 "with SSL_NO_VERIFY!");
```
Comment (mdempsky) [inline tools/tpm2_getekcertificate.c]: You want a space before "with"
